  -- MySQL Script generated by MySQL Workbench
  -- Tue May 14 13:00:58 2024
  -- Model: New Model    Version: 1.0
  -- MySQL Workbench Forward Engineering

  SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
  SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
  SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

  -- -----------------------------------------------------
  -- Schema mydb
  -- -----------------------------------------------------
  -- -----------------------------------------------------
  -- Schema cocinados
  -- -----------------------------------------------------s
  -- -----------------------------------------------------
  -- Schema cocinados
  -- -----------------------------------------------------
  CREATE SCHEMA IF NOT EXISTS `cocinados` DEFAULT CHARACTER SET utf8mb4 ;
  USE `cocinados` ;

  -- -----------------------------------------------------
  -- Table `cocinados`.`recetas`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `cocinados`.`recetas` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(255) NOT NULL,
    `tiempo_elaboracion` INT(11) NOT NULL,
    `imagen` VARCHAR(255) NULL DEFAULT NULL,
    `descripcion` VARCHAR(255) NULL DEFAULT NULL,
    `calorias` INT(11) NOT NULL,
    `num_personas` INT(11) NOT NULL,
    `tipo_plato` VARCHAR(255) NOT NULL,
    `nacionalidad` VARCHAR(255) NOT NULL,
    `tipo_dieta` VARCHAR(255) NOT NULL,
    `metodo_elaboracion` VARCHAR(255) NOT NULL,
    `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `ingrediente_especial` VARCHAR(255) NULL DEFAULT NULL, 
    PRIMARY KEY (`id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 52
  DEFAULT CHARACTER SET = utf8mb4;

  -- -----------------------------------------------------
  -- Table `cocinados`.`pasos`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `cocinados`.`pasos` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `receta_id` INT(11) NOT NULL,
    `paso` TEXT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `receta_id` (`receta_id` ASC),
    CONSTRAINT `pasos_ibfk_1`
      FOREIGN KEY (`receta_id`)
      REFERENCES `cocinados`.`recetas` (`id`)
      ON DELETE CASCADE
  )
  ENGINE = InnoDB
  AUTO_INCREMENT = 56
  DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `cocinados`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cocinados`.`ingredientes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `receta_id` INT(11) NOT NULL,
  `ingrediente` VARCHAR(255) NOT NULL,
  `cantidad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `receta_id` (`receta_id` ASC),
  CONSTRAINT `ingredientes_ibfk_1`
    FOREIGN KEY (`receta_id`)
    REFERENCES `cocinados`.`recetas` (`id`)
    ON DELETE CASCADE
)
ENGINE = InnoDB
AUTO_INCREMENT = 94
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `cocinados`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cocinados`.`usuarios` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `apellidos` VARCHAR(50) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(100) NULL DEFAULT NULL,
  `contrasena` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `correo_electronico` (`correo_electronico` ASC)
)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4;


  SET SQL_MODE=@OLD_SQL_MODE;
  SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
  SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
